version: '3.8'
services:
  mongo-dev:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - tasks_network

  mongo-test:
    image: mongo
    ports:
      - '27019:27017'
    networks:
      - tasks_network

volumes:
  mongo-data:

networks:
  tasks_network:
